[package]
name = "away"
version = "0.1.2"
authors = ["Carman Babin <CBabin@slb.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.10"
inputbot = "0.4.0"
device_query = "0.2.3"